Config.BunkerCrafting = {
    {
        itemName = "glasscutter",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 5000,
        NeedItems = {
            ['refined_scrap'] = 2,
            ['refined_copper'] = 2,
            ["refined_steel"] = 2,
            ["refined_rubber"] = 1,
            ["refined_glass"] = 4,
        },
        min = 1,
        max = 669,
    },
    {
        itemName = "gps_jammer",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 0,
        NeedItems = {
            ["metalscrap"] = 20,
            ["rubber"] = 20,
            ["plastic"] = 20,
            ["glass"] = 20,
        },
        min = 1,
        max = 669,
    },
    {
        itemName = "web_proxy",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 100,
        NeedItems = {
            ['refined_scrap'] = 1,
            ["refined_rubber"] = 1,
            ["refined_glass"] = 1,
        },
        min = 1,
        max = 669,
    },
}