Config = {}
Config.UseTruckerJob = true -- true = The shops stock is based on when truckers refill it | false = shop inventory never runs out
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
Config.ShopsInvJsonFile = './json/shops-inventory.json' -- json file location

Config.SellCasinoChips = {
    enable = false,
    coords = vector4(950.37, 34.72, 71.87, 33.82),
    radius = 1.5,
    ped = 's_m_y_casino_01'
}

-- optional requiredJob = {'police', 'ambulance'}
-- optional requiredGang = {'ballas', 'vagps'}
-- optional requiredLicense = {'driver', 'business', 'weapon'}

Config.Products = {
    ["normal"] = {
        ["name"] = "247 Supermarket",
        ["category"] = "Supermarket",
        ["job"] = "",
        ["categoryList"] = {
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Sweet"] = "Sweet for your mood.",
            ["Other"] = "Other items for your needs.",
        },
        ["itemList"] = {
            ["Foods"] = {
                { name = "tosti", price = 2, amount = 10, info = {}, type = "item", },
                { name = "sandwich", price = 2, amount = 10, info = {}, type = "item", },
            },
            ["Drinks"] = {
                { name = "water_bottle", price = 1, amount = 10, info = {}, type = "item", },
                { name = "cocacola", price = 2, amount = 10, info = {}, type = "item", },
                { name = "pepsi", price = 2, amount = 10, info = {}, type = "item", },
                { name = "drpepper", price = 2, amount = 10, info = {}, type = "item", },
                { name = "mountaindew", price = 2, amount = 10, info = {}, type = "item", },
                { name = "water", price = 2, amount = 10, info = {}, type = "item", },
                { name = "coffee", price = 2, amount = 10, info = {}, type = "item", },
                { name = "tea", price = 2, amount = 10, info = {}, type = "item", },
                { name = "hotchocolate", price = 2, amount = 10, info = {}, type = "item", },
                { name = "dirtywater", price = 2, amount = 10, info = {}, type = "item", },
            },
            ["Sweet"] = {
                { name = "twerks_candy", price = 1, amount = 10, info = {}, type = "item", },
                { name = "snikkel_candy", price = 1, amount = 10, info = {}, type = "item", },
                { name = "peanutmandms", price = 5, amount = 10, info = {}, type = "item", },
                { name = "hersheysbar", price = 6, amount = 10, info = {}, type = "item", },
            },
            ["Other"] = {
                { name = "lighter", price = 3, amount = 1, info = {}, type = "item", },
                { name = "burger_bun", price = 5, amount = 50, info = {}, type = "item", },
                { name = "burger_raw", price = 5, amount = 50, info = {}, type = "item", },
                { name = "burger_tomato", price = 5, amount = 50, info = {}, type = "item", },
                { name = "burger_lettuce", price = 5, amount = 50, info = {}, type = "item", },
                { name = "burger_potato", price = 5, amount = 50, info = {}, type = "item", },
                { name = "burger_sodasyrup", price = 5, amount = 50, info = {}, type = "item", },
            },
        }
    },
    ["liquor"] = {
        ["name"] = "liquor Supermarket",
        ["category"] = "Supermarket",
        ["job"] = "",
        ["categoryList"] = {
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Beer"] = "Beer for your thirst.",
            ["Sweet"] = "Sweet for your mood.",
            ["Other"] = "Other items for your needs.",
        },
        ["itemList"] = {
            ["Beer"] = {
                { name = "beer", price = 20, amount = 10, info = {}, type = "item", },
                { name = "whiskey", price = 40, amount = 10, info = {}, type = "item", },
                { name = "vodka", price = 50, amount = 10, info = {}, type = "item", },
                { name = "corona", price = 50, amount = 10, info = {}, type = "item", },
                { name = "corona6pack", price = 50, amount = 10, info = {}, type = "item", },
                { name = "budweiser", price = 50, amount = 10, info = {}, type = "item", },
                { name = "budweiser6pack", price = 50, amount = 10, info = {}, type = "item", },
            },
            ["Foods"] = {
                { name = "tosti", price = 2, amount = 10, info = {}, type = "item", },
                { name = "sandwich", price = 2, amount = 10, info = {}, type = "item", },
            },
            ["Drinks"] = {
                { name = "water_bottle", price = 1, amount = 10, info = {}, type = "item", },
                { name = "cocacola", price = 2, amount = 10, info = {}, type = "item", },
                { name = "pepsi", price = 2, amount = 10, info = {}, type = "item", },
                { name = "drpepper", price = 2, amount = 10, info = {}, type = "item", },
                { name = "mountaindew", price = 2, amount = 10, info = {}, type = "item", },
                { name = "water", price = 2, amount = 10, info = {}, type = "item", },
                { name = "coffee", price = 2, amount = 10, info = {}, type = "item", },
                { name = "tea", price = 2, amount = 10, info = {}, type = "item", },
                { name = "hotchocolate", price = 2, amount = 10, info = {}, type = "item", },
                { name = "dirtywater", price = 2, amount = 10, info = {}, type = "item", },
            },
            ["Sweet"] = {
                { name = "twerks_candy", price = 1, amount = 10, info = {}, type = "item", },
                { name = "snikkel_candy", price = 1, amount = 10, info = {}, type = "item", },
                { name = "peanutmandms", price = 5, amount = 10, info = {}, type = "item", },
                { name = "hersheysbar", price = 6, amount = 10, info = {}, type = "item", },
            },
            ["Other"] = {
                { name = "lighter", price = 1, amount = 50, info = {}, type = "item", },
            },
        }
    },
    ["hardware"] = {
        ["name"] = "Hardware Store",
        ["category"] = "Store",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["HardWare"] = "Diverse items for various needs.",
            ["Equipments"] = "Diverse items for various needs.",
        },
        ["itemList"] = {
            ["General"] = {
                { name = 'weapon_briefcase', price = 400,  amount = 1,  info = {}, type = 'item'},
                { name = 'weapon_briefcase_02', price = 450,  amount = 1,  info = {}, type = 'item'},
                { name = 'notebook',  price = 10, amount = 1, info = {}, type = 'item'},
            },
            ["HardWare"] = {
                { name = 'weapon_crowbar', price = 1500, amount = 1, info = {}, type = 'item'},
                { name = 'weapon_hammer', price = 1000, amount = 1, info = {}, type = 'item'},
                { name = 'weapon_hatchet',     price = 500, amount = 1,  info = {}, type = 'item'},
                { name = 'weapon_wrench',price = 500, amount = 1,  info = {}, type = 'item'},
                { name = 'weapon_battleaxe',     price = 500, amount = 1,  info = {}, type = 'item'},
            },
            ["Equipments"] = {
                { name = 'diving_gear',      price = 2500, amount = 5, info = {}, type = 'item'},
                { name = 'diving_fill',      price = 1500, amount = 5, info = {}, type = 'item'},
                { name = 'parachute',price = 2500, amount = 10, info = {}, type = 'item'},
                { name = 'repairkit',       price = 500,  amount = 10,  info = {}, type = 'item'},
                { name = "syphoningkit", price = 5000, amount = 1, info = { gasamount = 0 }, type = "item"},
            },        
        },
    },
    ["weedshop"] = {
        ["name"] = "Weed Shop",
        ["category"] = "Weed",
        ["job"] = "",
        ["categoryList"] = {
            ["Weed"] = "Unhealthy?",
        },
        ["itemList"] = {
            ["Weed"] = {
                { name = "lighter", price = 1, amount = 1, info = {}, type = "item", },
                { name = "rolling_paper", price = 2, amount = 10, info = {}, type = "item", },
                { name = "empty_weed_bag", price = 2, amount = 10, info = {}, type = "item", },
                { name = "weed_nutrition", price = 20, amount = 10, info = {}, type = "item", },
            },
        }
    },
    ["paintshop"] = {
        ["name"] = "Paint Shop",
        ["category"] = "Paint",
        ["job"] = "",
        ["categoryList"] = {
            ["Paint"] = "Paint?",
        },
        ["itemList"] = {
            ["Paint"] = {
                { name = "spraycan", price = 10000, amount = 1, info = {}, type = "item", },
                { name = "spray_remover", price = 15000, amount = 1, info = {}, type = "item", },
            },
        }
    },
    ["casino"] = {
        ["name"] = "Casino Shop",
        ["category"] = "casino",
        ["job"] = "",
        ["categoryList"] = {
            ["casino"] = "Chips?",
        },
        ["itemList"] = {
            ["casino"] = {
                { name = 'casinochips',  price = 100,   amount = 9999, info = {}, type = 'item'},
            },
        }
    },
    ["weapons"] = {
        ["name"] = "Weapon Store",
        ["category"] = "Store",
        ["job"] = "",
        ["categoryList"] = {
            ["Weapon"] = "Lethal tools for self-defense.",
            ["knife"] = "Lethal tools for self-defense.",
            ["Spray"] = "Lethal Equipemeny for Guns.",
        },
        ["itemList"] = {
            ["Weapon"] = {
                { name = 'armor',                      price = 1500,  amount = 10, info = {}, type = 'item'},
                { name = 'weapon_snspistol',            price = 15000, amount = 1,   info = {}, type = 'weapon',},
                { name = 'weapon_flashlight',          price = 500,  amount = 1, info = {}, type = 'item'},
                { name = 'weapon_fireextinguisher', 	     price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_bat',                 price = 1000,  amount = 1, info = {}, type = 'weapon'},
                { name = 'weapon_golfclub',            price = 1000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_knuckle',             price = 1500, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_stone_hatchet',      price = 1000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_poolcue',            price = 2000, amount = 1,   info = {}, type = 'weapon'},
            },
            ["knife"] = {
                { name = 'weapon_knife',               price = 1500, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_dagger',              price = 500,  amount = 1, info = {}, type = 'weapon'},
                { name = 'weapon_machete',             price = 2500, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_switchblade',         price = 1200, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_urbanrbfknife',      price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_stainedrbfknife',    price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_slaughterbfknife',   price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_scorchedbfknife',    price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_safaribfknife', 	 price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_karambitknife', 	 price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_huntsmanknife', 	 price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_gutknife', 	 	     price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_forestbfknife', 	 price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_bluebfknife', 	     price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_bfknife', 	 	 price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_chbfknife', 	 		 price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_crimsonbfknife', 	     price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_fadebfknife', 	 price = 2000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'weapon_flipknife', 	 	 price = 2000, amount = 1,   info = {}, type = 'weapon'},
            },
            ["Spray"] = {
                { name = 'patriotcamo_attachment',          price = 5000, amount = 1,   info = {}, type = 'weapon'},
                { name = 'boomcamo_attachment',    price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'geocamo_attachment',       price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'zebracamo_attachment',        price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'leopardcamo_attachment',      price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'perseuscamo_attachment',    price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'sessantacamo_attachment',    price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'skullcamo_attachment',   price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'woodcamo_attachment',      price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'brushcamo_attachment',       price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'digicamo_attachment',      price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_0',       price = 2000, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_1',              price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_2',              price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_3',              price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_6',              price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_7',              price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_0',              price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_1',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_2',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_3',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_4',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_5',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_6',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_7',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_8',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_9',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_10',          price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_11',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_12',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_13',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_14',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_14',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_16',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_17',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_18',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_19',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_20',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_21',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_22',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_23',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_24',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_25',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_26',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_27',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_28',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_29',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_30',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_31',         price = 1400, amount = 1,   info = {}, type = 'item'},
                { name = 'weapontint_mk2_32',         price = 1400, amount = 1,   info = {}, type = 'item'},
            },
        },
    },
    ["electronic"] = {
        ["name"] = "Electronic Store",
        ["category"] = "Store",
        ["job"] = "",
        ["categoryList"] = {
            ["Electronic"] = "Diverse items for various needs.",
        },
        ["itemList"] = {
            ["Electronic"] = {
                { name = 'phone', price = 2000, amount = 1, info = {}, type = 'item', },
                { name = 'radio', price = 3000, amount = 10, info = {}, type = 'item', },
                { name = 'camera', price = 4000, amount = 1, info = {}, type = 'item', },
                { name = 'boombox', price = 200, amount = 1, info = {}, type = 'item', },
            },
        }
    },
    ["prison"] = {
        ["name"] = "prison Shop",
        ["category"] = "Store",
        ["job"] = "",
        ["categoryList"] = {
            ["Prison"] = "Diverse items for various needs.",
        },
        ["itemList"] = {
            ["Prison"] = {
                { name = 'sandwich', price = 4, amount = 10, info = {}, type = 'item', },
                { name = 'water_bottle', price = 4, amount = 10, info = {}, type = 'item', },
            },
        }
    },
    ["police"] = {
        ["name"] = "Police Armory",
        ["category"] = "Store",
        ["job"] = "police",
        ["categoryList"] = {
            ["Weapons"] = "Diverse items for Police Officers",
            ["Ammo"] = "Diverse items for Police Officers",
            ["Equipments"] = "Diverse items for Police Officers",
        },
        ["itemList"] = {
            ["Weapons"] = {
                { name = 'weapon_stungun', price = 3000, amount = 1, info = {}, type = 'item', },
                { name = 'weapon_knife', price = 0, amount = 1, info = {}, type = 'item', },
                { name = 'weapon_nightstick', price = 0, amount = 1, info = {}, type = 'item', },
                { name = 'police_stormram', price = 0, amount = 1, info = {}, type = 'item', },
                { name = 'weapon_fireextinguisher', price = 0, amount = 1, info = {}, type = 'item', },
            },
            ["Ammo"] = {
                { name = 'pistol_ammo', price = 20, amount = 10, info = {}, type = 'item', },
                { name = 'smg_ammo', price = 25, amount = 10, info = {}, type = 'item', },
                { name = 'shotgun_ammo', price = 30, amount = 10, info = {}, type = 'item', },
                { name = 'rifle_ammo', price = 30, amount = 10, info = {}, type = 'item', },
                { name = 'mg_ammo', price = 45, amount = 10, info = {}, type = 'item', },
                { name = 'emp_ammo', price = 40, amount = 10, info = {}, type = 'item', },
                { name = 'snp_ammo', price = 50, amount = 10, info = {}, type = 'item', },
            },
            ["Equipments"] = {
                { name = 'oxy', price = 30, amount = 10, info = {}, type = 'item', },
                { name = 'armor', price = 200, amount = 10, info = {}, type = 'item', },
                { name = 'heavyarmor', price = 300, amount = 10, info = {}, type = 'item', },
                { name = 'weapon_flashlight', price = 0, amount = 10, info = {}, type = 'item', },
                { name = 'empty_evidence_bag', price = 0, amount = 10, info = {}, type = 'item', },
                { name = 'parachute', price = 1000, amount = 1, info = {}, type = 'item', },
                { name = 'diving_gear', price = 2000, amount = 1, info = {}, type = 'item', },
                { name = 'diving_fill', price = 1000, amount = 1, info = {}, type = 'item', },
                { name = 'nightvision', price = 0, amount = 1, info = {}, type = 'item', },
                { name = 'thermalgoggles', price = 0, amount = 1, info = {}, type = 'item', },
                { name = 'gopro', price = 0, amount = 1, info = {}, type = 'item', },
                { name = 'repairkit', price = 100, amount = 1, info = {}, type = 'item', },
                { name = 'handcuffs', price = 1000, amount = 1, info = {}, type = 'item', },
                { name = 'binoculars', price = 2000, amount = 1, info = {}, type = 'item', },
            },
        },
    },
    ["mechanic"] = {
        ["name"] = "Mechanic Store",
        ["category"] = "Store",
        ["job"] = "",
        ["categoryList"] = {
            ["Mechanic"] = "Diverse items for various needs.",
        },
        ["itemList"] = {
            ["Mechanic"] = {
                { name = 'veh_toolbox',       price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_armor',         price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_brakes',        price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_engine',        price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_suspension',    price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_transmission',  price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_turbo',         price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_interior',      price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_exterior',      price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_wheels',        price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_neons',         price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_xenons',        price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_tint',          price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'veh_plates',        price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'nitrous',           price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'tunerlaptop',       price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'repairkit',         price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'advancedrepairkit', price = 5000, amount = 50, info = {}, type = 'item' },
                { name = 'tirerepairkit',     price = 5000, amount = 50, info = {}, type = 'item' },
            },
        }
    },
    ["pharmacy"] = {
        ["name"] = "Pharmacy Store",
        ["category"] = "Store",
        ["job"] = "",
        ["categoryList"] = {
            ["Pharmacy"] = "Diverse items for various needs.",
        },
        ["itemList"] = {
            ["Pharmacy"] = {
                { name = 'ifaks',             price = 10, amount = 10, info = {}, type = 'item' },
                { name = 'painkillers',       price = 1, amount = 10, info = {}, type = 'item' },
                { name = 'bandage',           price = 3, amount = 100, info = {}, type = 'item' },
                { name = 'walkstick',         price = 8, amount = 10, info = {}, type = 'item' },
            },
        }
    },
}
Config.Locations = {
    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(24.329399, -1348.247, 29.497028, 319.14852),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,        
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(26.45, -1315.51, 29.62, 0.07)
    },
    ["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(-3037.705, 584.91229, 7.9089345, 73.39199),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },
    ["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(-3241.053, 999.85498, 12.830711, 44.825496),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },
    ["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(1727.2562, 6414.1333, 35.037242, 300.14434),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },
    ["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(1960.6086, 3738.9367, 32.343761, 347.77682),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },
    ["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(548.98052, 2672.4318, 42.156543, 154.77252),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(541.54, 2663.53, 42.17, 120.51)
    },
    ["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(2679.1584, 3278.7565, 55.241149, 26.022966),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },
    ["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(2558.4936, 380.73962, 108.62298, 52.827499),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(2553.24, 399.73, 108.56, 344.86)
    },
    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ['coords'] = vector4(372.22378, 325.26589, 103.56641, 297.69049),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 2,
        ["delivery"] = vector4(379.97, 357.3, 102.56, 26.42)
    },
    -- LTD Gasoline Locations
    ["ltdgasoline"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-40.51, -1747.45, 29.29, 326.39)
    },
    ["ltdgasoline2"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-702.89, -917.44, 19.21, 181.96)
    },
    ["ltdgasoline3"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },
    ["ltdgasoline4"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1160.62, -312.06, 69.28, 3.77)
    },
    ["ltdgasoline5"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },
    ["ltdgasoline5"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(291.94, -1272.62, 29.52, 3.97),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "normal",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(294.49, -1251.92, 29.42, 187.7)
    },
    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "liquor",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },
    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "liquor",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },
    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "liquor",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },
    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "liquor",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },
    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "liquor",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1129.73, -989.27, 45.97, 280.98)
    },
    -- Cayoensure
    ["robsliquor6"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(4466.11, -4463.75, 4.3, 200.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = "liquor",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(4489.89, -4443.41, 4.96, 206.93)
    },
    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(2736.9658, 3462.3054, 55.695678, 338.75286),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = "hardware",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },
    ["hardware2"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(45.68, -1749.04, 29.61, 53.13),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = "hardware",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(89.15, -1745.29, 30.09, 315.25)
    },
    ["hardware3"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Hardware Store",
        ["products"] = "hardware",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },
    -- Ammunation Locations
    ["ammunation"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-661.96, -933.53, 21.83, 177.05),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(-660.61, -938.14, 21.83, 167.22)
    },
    ["ammunation2"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(809.68, -2159.13, 29.62, 1.43),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(820.97, -2146.7, 28.71, 359.98)
    },
    ["ammunation3"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(1687.17, 3755.47, 34.34, 163.69)
    },
    ["ammunation4"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(-341.72, 6098.49, 31.32, 11.05)
    },
    ["ammunation5"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(253.63, -51.02, 69.94, 72.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(249.0, -50.64, 69.94, 60.71)
    },
    ["ammunation6"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(23.0, -1105.67, 29.8, 162.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(-5.82, -1107.48, 29.0, 164.32)
    },
    ["ammunation7"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(2567.48, 292.59, 108.73, 349.68),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(2578.77, 285.53, 108.61, 277.2)
    },
    ["ammunation8"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(-1127.67, 2708.18, 18.8, 41.76)
    },
    ["ammunation9"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(841.92, -1035.32, 28.19, 1.56),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(847.83, -1020.36, 27.88, 88.29)
    },
    ["ammunation10"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(-1302.44, -385.23, 36.62, 303.79)
    },
    ["ammunation11"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = "weapons",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(-3183.6, 1084.35, 20.84, 68.13)
    },
    -- Casino Locations
    ["casino"] = {
        ["label"] = "Diamond Casino",
        ["coords"] = vector4(953.84, 56.29, 75.44, 171.03),
        ["ped"] = 'csb_tomcasino',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-coins",
        ["targetLabel"] = "Buy Chips",
        ["products"] = "casino",
        ["showblip"] = true,
        ["blipsprite"] = 617,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(972.6, 9.22, 81.04, 233.38)
    },
    ["casinobar"] = {
        ["label"] = "Casino Bar",
        ["coords"] = vector4(968.13, 29.85, 74.88, 208.86),
        ["ped"] = 'a_m_y_smartcaspat_01',
        ["scenario"] = "WORLD_HUMAN_VALET",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = "liquor",
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
       -- ["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },
    ["electronic"] = {
        ["label"] = "Electronics Store",
        ["coords"] = vector4(1134.1, -467.97, 66.49, 184.38),
        ["ped"] = 'a_m_y_stwhi_02',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-mobile",
        ["targetLabel"] = "Open Electronic shop",
        ["products"] = "electronic",
        ["showblip"] = true,
        ["blipsprite"] = 89,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 1,
        --["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },
    
    ["electronic1"] = {
        ["label"] = "Electronics Store",
        ["coords"] = vector4(-626.13, -277.65, 35.58, 128.78),
        ["ped"] = 'a_m_y_stwhi_02',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-mobile",
        ["targetLabel"] = "Open Electronic shop",
        ["products"] = "electronic",
        ["showblip"] = true,
        ["blipsprite"] = 89,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 1,
        --["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },
    ["electronic2"] = {
        ["label"] = "Electronics Store",
        ["coords"] = vector4(-1530.11, -401.87, 35.64, 232.58),
        ["ped"] = 'a_m_y_stwhi_02',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-mobile",
        ["targetLabel"] = "Open Electronic shop",
        ["products"] = "electronic",
        ["showblip"] = true,
        ["blipsprite"] = 89,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 1,
        --["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },
    ["electronic3"] = {
        ["label"] = "Electronics Store",
        ["coords"] = vector4(-660.58, -857.11, 24.54, 274.47),
        ["ped"] = 'a_m_y_stwhi_02',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-mobile",
        ["targetLabel"] = "Open Electronic shop",
        ["products"] = "electronic",
        ["showblip"] = true,
        ["blipsprite"] = 89,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 1,
        --["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },
    ["electronic"] = {
        ["label"] = "Electronics Store",
        ["coords"] = vector4(212.60856, -1507.437, 29.294555, 220.72323),
        ["ped"] = 'a_m_y_stwhi_02',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-mobile",
        ["targetLabel"] = "Open Electronic shop",
        ["products"] = "electronic",
        ["showblip"] = true,
        ["blipsprite"] = 89,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 1,
        ["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },
    ["electronic"] = {
        ["label"] = "Electronics Store",
        ["coords"] = vector4(212.60856, -1507.437, 29.294555, 220.72323),
        ["ped"] = 'a_m_y_stwhi_02',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-mobile",
        ["targetLabel"] = "Open Electronic shop",
        ["products"] = "electronic",
        ["showblip"] = true,
        ["blipsprite"] = 89,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 1,
        ["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },
    -- Weedshop Locations
    ["weedshop"] = {
        ["label"] = "Smoke On The Water",
        ["coords"] = vector4(-1168.26, -1573.2, 4.66, 105.24),
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cannabis",
        ["targetLabel"] = "Open Weed Shop",
        ["products"] = "weedshop",
        ["showblip"] = true,
        ["blipsprite"] = 140,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1162.13, -1568.57, 4.39, 328.52)
    },
    -- Sea Word Locations
    -- ["seaword"] = {
    --     ["label"] = "Paint Shop",
    --     ["coords"] = vector4(-1687.03, -1072.18, 13.15, 52.93),
    --     ["ped"] = 'a_m_y_beach_01',
    --     ["scenario"] = "WORLD_HUMAN_STAND_IMPATIENT",
    --     ["radius"] = 1.5,
    --     ["targetIcon"] = "fas fa-fish",
    --     ["targetLabel"] = "Buy",
    --     ["products"] = "gearshop",
    --     ["showblip"] = true,
    --     ["blipsprite"] = 52,
    --     ["blipscale"] = 0.6,
    --     ["blipcolor"] = 0,
    --     ["delivery"] = vector4(-1674.18, -1073.7, 13.15, 333.56)
    -- },
    ["prison"] = {
        ["label"] = "Canteen Shop",
        ["coords"] = vector4(1777.59, 2560.52, 45.62, 187.83),
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cannabis",
        ["targetLabel"] = "Open Shop",
        ["products"] = "prison",
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1845.8175, 2585.9312, 45.6721, 96.7577)
    },
    ["police"] = {
        ["label"] = "Police Shop",
        ["coords"] = vector4(-1106.78, -822.82, 14.28, 212.92),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Armory",
        ["products"] = "police",
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
    ["police2"] = {
        ["label"] = "Police Shop",
        ["coords"] = vector4(-437.32, 5987.9, 31.72, 91.5892),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Armory",
        ["products"] = "police",
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
    ["police3"] = {
        ["label"] = "Police Shop",
        ["coords"] = vector4(1837.81, 3681.54, 38.93, 2.18),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Armory",
        ["products"] = "police",
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
    ["mechanic"] = {
        ["label"] = "Mechanic Store",
        ["coords"] = vector4(-343.66, -140.78, 39.02, 0),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Store",
        ["products"] = "mechanic",
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
    ["pharmacy"] = {
        ["label"] = "Pharmacy Store",
        ["coords"] = vector4(-1830.0, -380.63, 49.4, 51.68),
        ["ped"] = 's_f_y_scrubs_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Store",
        ["products"] = "pharmacy",
        ["showblip"] = true,
        ["blipsprite"] = 403,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 48,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
    ["pharmacy2"] = {
        ["label"] = "Pharmacy Store",
        ["coords"] = vector4(318.24, -1078.4, 29.48, 9.58),
        ["ped"] = 's_f_y_scrubs_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Store",
        ["products"] = "pharmacy",
        ["showblip"] = true,
        ["blipsprite"] = 403,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 48,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
    ["pharmacy3"] = {
        ["label"] = "Pharmacy Store",
        ["coords"] = vector4(70.79, -813.82, 31.33, 252.69),
        ["ped"] = 's_f_y_scrubs_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Store",
        ["products"] = "pharmacy",
        ["showblip"] = true,
        ["blipsprite"] = 403,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 48,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
    ["pharmacy4"] = {
        ["label"] = "Pharmacy Store",
        ["coords"] = vector4(-171.62, 6387.21, 31.5, 148.29),
        ["ped"] = 's_f_y_scrubs_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Store",
        ["products"] = "pharmacy",
        ["showblip"] = true,
        ["blipsprite"] = 403,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 48,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
    ["pharmacy5"] = {
        ["label"] = "Pharmacy Store",
        ["coords"] = vector4(-507.0, 292.49, 83.39, 170.57),
        ["ped"] = 's_f_y_scrubs_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Store",
        ["products"] = "pharmacy",
        ["showblip"] = true,
        ["blipsprite"] = 403,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 48,
        --["delivery"] = vector4(459.0441, -1008.0366, 28.2627, 271.4695)
    },
}