Config = Config or {}
Config.BillingCommissions = { -- This is a percentage (0.10) == 10%
    mechanic = 0.10,
    popsdiner = 0.10
}
Config.Linux = false      -- True if linux
Config.TweetDuration = 240 -- How many hours to load tweets (12 will load the past 12 hours of tweets)
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 244
Config.PhoneApplications = {
    ['phone'] = {
        app = 'phone',
        color = '#04b543',
        icon = 'fa fa-phone-alt',
        tooltipText = 'جوال',
        tooltipPos = 'top',
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ['whatsapp'] = {
        app = 'whatsapp',
        color = '#25d366',
        icon = 'fab fa-whatsapp',
        tooltipText = 'واتس اب',
        tooltipPos = 'top',
        style = 'font-size: 2.8vh',
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ['settings'] = {
        app = 'settings',
        color = '#636e72',
        icon = 'fa fa-cogs',
        tooltipText = 'الاعدادات',
        tooltipPos = 'top',
        style = 'padding-right: .08vh; font-size: 2.3vh',
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ['twitter'] = {
        app = 'twitter',
        color = '#1da1f2',
        icon = 'fab fa-twitter',
        tooltipText = 'تويتر',
        tooltipPos = 'top',
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ['garage'] = {
        app = 'garage',
        color = '#575fcf',
        icon = 'fas fa-car',
        tooltipText = 'الكراج',
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ['mail'] = {
        app = 'mail',
        color = '#ff002f',
        icon = 'fas fa-envelope',
        tooltipText = 'الايميل',
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ['advert'] = {
        app = 'advert',
        color = '#ff8f1a',
        icon = 'fas fa-bullhorn',
        tooltipText = 'الاعلانات',
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ['bank'] = {
        app = 'bank',
        color = '#9c88ff',
        icon = 'fas fa-money-check',
        tooltipText = 'البنك',
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    ['crypto'] = {
        app = 'crypto',
        color = '#004682',
        icon = 'fas fa-coins',
        tooltipText = 'كريبتو',
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ['racing'] = {
        app = 'racing',
        color = '#353b48',
        icon = 'fas fa-flag-checkered',
        tooltipText = 'السباقات',
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ['houses'] = {
        app = 'houses',
        color = '#27ae60',
        icon = 'fas fa-home',
        tooltipText = 'البيوت',
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ['lawyers'] = {
        app = 'lawyers',
        color = '#26d4ce',
        icon = 'fas fa-briefcase',
        tooltipText = 'الخدمات',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ['gallery'] = {
        app = 'gallery',
        color = '#AC1D2C',
        icon = 'fas fa-image',
        tooltipText = 'الصور',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ['camera'] = {
        app = 'camera',
        color = '#AC1D2C',
        icon = 'fas fa-camera',
        tooltipText = 'الكاميرا',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    ['meos'] = {
        app = 'meos',
        color = '#004682',
        icon = 'fas fa-desktop',
        tooltipText = 'MDT',
        job = 'police',
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    ["meos"] = {
        app = "meos",
        color = "#004682",
        icon = "fas fa-ad",
        tooltipText = "MDT",
        job = "sheriff",
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
}
Config.MaxSlots = 20

Config.StoreApps = {
    ['territory'] = {
        app = 'territory',
        color = '#353b48',
        icon = 'fas fa-globe-europe',
        tooltipText = 'Territorium',
        tooltipPos = 'right',
        style = '',
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
        password = true,
        creator = 'QBCore',
        title = 'Territory',
    },
}
